theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MUp}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "bluetooth"
mac = "5A:5A:5A:A6:17:D1"
label = "Headphones"

[[block]]
block = "net"
device = "wlp170s0"
ssid = true
signal_strength = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
device = "/sys/class/power_supply/BAT1"
interval = 10
format = "{percentage}%"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
