[theme] 
name = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
separator = " | "
separator_fg = "#839496"
separator_bg = "#000000"

[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = ""
show_bar = true
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mupb}"
format_swap = "{SUpb}"

[[block]]
block = "cpu"
interval = 1
format = "{utilizationbar}"

[[block]]
block = "net"
device = "wlp55s0"
ssid = true
signal_strength = true
signal_strength_bar = true
speed_up = false
speed_down = false
interval = 5
hide_missing = true

[[block]]
block = "time"
interval = 60
format = "%a %b %e %R"

[[block]]
block = "sound"
bar = true
show_volume_when_muted = true
step_width = 5

