# uncomment for profiling
# zmodload zsh/zprof

# do not edit this file. put files in the dir below.
for FN in $HOME/.config/zshrc.d/*.sh ; do
    source "$FN"
done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# uncomment for profiling
# zprof
